stages:
  - build
  - test-unit
  - test-functional

build:
  image: kkarczmarczyk/node-yarn
  stage: build
  script:
    - yarn install
    - yarn build

test-unit:
  image: docker/compose
  stage: test-unit
  script:
    - ./docker/run-unit-tests

test-functional:
  image: docker/compose
  stage: test-functional
  script:
    - ./docker/run-functional-tests


