image: "alpine:3.7"

before_script:
  - |
    function setup_test_dependencies() {
      apk add -U openssl curl tar gzip bash ca-certificates git python2 py2-pip \
        && pip install docker-compose ;
    }
    function setup_docker() {
      if ! docker info &>/dev/null; then
        if [ -z "$DOCKER_HOST" ]; then
          export DOCKER_HOST='tcp://localhost:2375'
        fi
      fi
    }
    function publish_to_npm() {
      GIT_TAG=`git describe --tags --exact-match 2> /dev/null | cat`
      test -n "$GIT_TAG" \
        || return 0 \
        && echo "Package version to be published: $GIT_TAG" \
        && test "$GIT_TAG" = `jq '.version' package.json` \
        && echo "Checked: git tag matches package.json version" \
        && yarn publish --prod --no-progress --non-interactive --new-version "$GIT_TAG" --access public ;
    }
    function setup_aws() {
      apk add -U openssl curl tar gzip bash ca-certificates python2 py2-pip \
        && pip install awscli ;
    }

stages:
  - test
  - deploy

test:
  image: "docker:17.12.0-ce"
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:17.12.0-ce-dind
  stage: test
  only:
    - branches
  except:
    - tags
    - master
  script:
    - setup_test_dependencies
    - setup_docker
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - ./docker/yarn install --no-progress
    - ./docker/run-all-tests

npm_deploy:
  image: "registry.gitlab.com/adsmurai/platform/docker-images/js-tools:dev-8.9"
  variables:
    DOCKER_DRIVER: overlay2
  stage: deploy
  only:
    - tags
  except:
    - branches
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}">.npmrc
    - yarn install --no-progress
    - yarn build
    - publish_to_npm

s3_deploy:
  image: "docker:17.12.0-ce"
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:17.12.0-ce-dind
  stage: deploy
  only:
    - master
  except:
    - tags
  script:
    - setup_aws
    - setup_docker
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - ./docker/yarn install --no-progress
    - ./docker/yarn build
    - aws s3 cp dist s3://com.adsmurai.js.libs --recursive --acl public-read
