image: registry.gitlab.com/adsmurai/platform/docker-registry/js-tools:dev-8.9

stages:
  - build
  - test-unit
  - test-functional

.build:
  stage: build
  script:
    - yarn install
    - yarn build

test-unit:
  services:
    - docker:dind
  stage: test-unit
  script:
    - ./docker/run-unit-tests

test-functional:
  services:
    - docker:dind
  stage: test-functional
  script:
    - ./docker/run-functional-tests


