image: "alpine:3.7"

before_script:
  - |
    function setup_script_dependencies() {
      apk add -U openssl curl tar gzip bash ca-certificates git python2 py2-pip \
        && pip install docker-compose ;
    }
    function setup_docker() {
      if ! docker info &>/dev/null; then
        if [ -z "$DOCKER_HOST" ]; then
          export DOCKER_HOST='tcp://localhost:2375'
        fi
      fi
    }
    function publish_to_npm() {
      GIT_TAG=`git describe --tags --exact-match 2> /dev/null | cat`
      test -n "$GIT_TAG" \
        && yarn publish --prod --no-progress --non-interactive --new-version "$GIT_TAG" --access public
    }

stages:
  - build
  - test
  - deploy

build:
  image: "registry.gitlab.com/adsmurai/platform/docker-images/js-tools:dev-8.9"
  stage: build
  cache:
    untracked: true
  script:
    - yarn install
    - yarn build

test:
  image: "docker:17.12.0-ce"
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:17.12.0-ce-dind
  stage: test
  cache:
    untracked: true
  script:
    - setup_script_dependencies
    - setup_docker
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - ./docker/run-all-tests

deploy:
  image: "registry.gitlab.com/adsmurai/platform/docker-images/js-tools:dev-8.9"
  stage: deploy
  only:
    - master
  cache:
    untracked: true
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - publish_to_npm
