#!/usr/bin/env bash

run(){
    declare -r script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
    declare bashlib_dir="${script_dir}/bashLib"
    source "${bashlib_dir}/commonLib.sh"

    scall "${script_dir}/run-unit-tests"
    declare -r unit_test_status=$?

    scall "${script_dir}/run-functional-tests"
    declare -r functional_test_status=$?

    declare -r test_status=$(( $functional_test_status | $unit_test_status ))
    return ${test_status}
}
run "$@"
