#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
${SCRIPT_DIR}/run-unit-tests
UNIT_TEST_STATUS=$?

${SCRIPT_DIR}/run-functional-tests
FUNCTIONAL_TEST_STATUS=$?

if [ $FUNCTIONAL_TEST_STATUS -ne 0 ]; then
    TEST_STATUS=$FUNCTIONAL_TEST_STATUS
else
    TEST_STATUS=$UNIT_TEST_STATUS
fi
